[manifest]
version = "1.0.0"
dump_lua = true
priority = 11 # Go after Bunco


[[patches]]
[patches.regex]
target = 'card.lua'
pattern = "(?<code>add_tag\\(Tag\\('tag_bunc_xmult'\\)\\)\n(?<indent>[ |\t]*?)play_sound\\('generic1'\\))"
position = 'at'
# line_prepend = "$indent"
payload = '''
if used_tarot.ability.set ~= "Alchemical" then
    $indent$code
$indent end
'''